[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
owo-colors = "4.2.2"
tokio = { version = "1.47.0", features = ["full"] }
